"""
PPT Agent — generates a .pptx slide deck using python-pptx.
Slide content is first generated by Gemini as structured JSON,
then assembled into a 4-slide deck.
"""
import json
import os
import uuid
from pathlib import Path

import google.generativeai as genai
from pptx import Presentation
from pptx.dml.color import RGBColor
from pptx.util import Inches, Pt


ARTIFACTS_DIR = Path(__file__).parent.parent / "artifacts"


def _parse_json_list(raw) -> list:
    """Parse a physician list that may be a Python list, a JSON string, or
    a JSON string with trailing prose (Gemini occasionally appends text)."""
    if not isinstance(raw, str):
        return raw if isinstance(raw, list) else []
    raw = raw.strip()
    # Find the opening bracket; skip any leading text the model prepended
    start = raw.find("[")
    if start == -1:
        start = raw.find("{")
    if start == -1:
        return []
    result, _ = json.JSONDecoder().raw_decode(raw[start:])
    if isinstance(result, list):
        return result
    if isinstance(result, dict):
        return [result]
    # Double-encoded: result is itself a JSON string
    if isinstance(result, str):
        return _parse_json_list(result)
    return []

# DocNexus brand colours
NAVY = RGBColor(0x1A, 0x2E, 0x4A)
TEAL = RGBColor(0x00, 0x8C, 0x8C)
WHITE = RGBColor(0xFF, 0xFF, 0xFF)
LIGHT_GREY = RGBColor(0xF2, 0xF2, 0xF2)


def load_prompt(name: str) -> str:
    path = Path(__file__).parent.parent / "prompts" / f"{name}.txt"
    return path.read_text(encoding="utf-8")


async def run_ppt_agent(
    topic: str,
    physician_list: str,
    icd10_codes: list[str] | None = None,
    slide_count: int = 4,
    style_notes: str = "",
) -> dict:
    try:
        physicians = _parse_json_list(physician_list)

        # --- Step 1: Ask Gemini to generate structured slide content ---
        genai.configure(api_key=os.environ["GOOGLE_API_KEY"])
        model = genai.GenerativeModel(
            model_name=os.environ.get("GEMINI_MODEL", "gemini-2.0-flash"),
            system_instruction=load_prompt("ppt_agent"),
        )

        prompt = (
            f"Topic: {topic}\n"
            f"ICD-10 codes in scope: {', '.join(icd10_codes or [])}\n"
            f"Style notes: {style_notes}\n\n"
            f"Physician data (JSON):\n{json.dumps(physicians, indent=2)}\n\n"
            "Return ONLY a valid JSON object — no markdown fences, no extra text."
        )

        import asyncio
        response = await asyncio.to_thread(model.generate_content, prompt)
        raw = response.text.strip()
        if raw.startswith("```"):
            raw = raw.split("```")[1]
            if raw.startswith("json"):
                raw = raw[4:]
        # Find first { so leading prose from the model doesn't break parsing,
        # then raw_decode so trailing text after the JSON object is ignored.
        start = raw.find("{")
        if start == -1:
            raise ValueError(f"No JSON object found in model response: {raw[:200]}")
        content, _ = json.JSONDecoder().raw_decode(raw[start:])

        # --- Step 2: Build the .pptx with python-pptx ---
        prs = Presentation()
        prs.slide_width = Inches(13.33)
        prs.slide_height = Inches(7.5)

        _build_title_slide(prs, content, icd10_codes or [])
        _build_overview_slide(prs, content)
        _build_insights_slide(prs, content)
        _build_table_slide(prs, content, physicians)

        artifact_id = str(uuid.uuid4())
        out_path = ARTIFACTS_DIR / f"{artifact_id}.pptx"
        prs.save(str(out_path))

        return {"artifact_id": artifact_id, "filename": "deck.pptx"}

    except Exception as exc:
        return {"error": True, "message": str(exc)}


# ── Slide builders ──────────────────────────────────────────────────────────

def _set_bg(slide, color: RGBColor):
    from pptx.oxml.ns import qn
    from lxml import etree

    bg = slide.background
    fill = bg.fill
    fill.solid()
    fill.fore_color.rgb = color


def _add_text_box(slide, text: str, left, top, width, height, font_size=18, bold=False, color=WHITE, wrap=True):
    from pptx.util import Inches, Pt
    txBox = slide.shapes.add_textbox(left, top, width, height)
    tf = txBox.text_frame
    tf.word_wrap = wrap
    p = tf.paragraphs[0]
    p.text = text
    run = p.runs[0]
    run.font.size = Pt(font_size)
    run.font.bold = bold
    run.font.color.rgb = color
    return txBox


def _build_title_slide(prs: Presentation, content: dict, icd10_codes: list[str]):
    blank_layout = prs.slide_layouts[6]
    slide = prs.slides.add_slide(blank_layout)
    _set_bg(slide, NAVY)

    _add_text_box(slide, content.get("title", "DocNexus Intelligence"), Inches(1), Inches(2), Inches(11.33), Inches(1.5), font_size=36, bold=True)
    _add_text_box(slide, content.get("subtitle", "Physician Intelligence Report"), Inches(1), Inches(3.8), Inches(11.33), Inches(0.8), font_size=22, color=TEAL)

    codes_label = f"ICD-10 scope: {', '.join(icd10_codes)}" if icd10_codes else ""
    if codes_label:
        _add_text_box(slide, codes_label, Inches(1), Inches(5.5), Inches(6), Inches(0.5), font_size=14, color=LIGHT_GREY)

    _add_text_box(slide, "Powered by DocNexus AI", Inches(9), Inches(6.8), Inches(3.5), Inches(0.5), font_size=11, color=LIGHT_GREY)


def _build_overview_slide(prs: Presentation, content: dict):
    blank_layout = prs.slide_layouts[6]
    slide = prs.slides.add_slide(blank_layout)
    _set_bg(slide, WHITE)

    _add_text_box(slide, "Physician Population Overview", Inches(0.5), Inches(0.3), Inches(12), Inches(0.8), font_size=28, bold=True, color=NAVY)

    overview = content.get("overview", {})
    total = overview.get("total_physicians", "N/A")
    top_specialties = ", ".join(overview.get("top_specialties", []))
    top_states = ", ".join(overview.get("top_states", []))

    _add_text_box(slide, f"Total Physicians: {total}", Inches(0.5), Inches(1.4), Inches(5), Inches(0.6), font_size=20, bold=True, color=TEAL)
    _add_text_box(slide, f"Top Specialties: {top_specialties}", Inches(0.5), Inches(2.2), Inches(12), Inches(0.7), font_size=16, color=NAVY)
    _add_text_box(slide, f"Top States: {top_states}", Inches(0.5), Inches(3.0), Inches(12), Inches(0.7), font_size=16, color=NAVY)


def _build_insights_slide(prs: Presentation, content: dict):
    blank_layout = prs.slide_layouts[6]
    slide = prs.slides.add_slide(blank_layout)
    _set_bg(slide, LIGHT_GREY)

    _add_text_box(slide, "Key Insights", Inches(0.5), Inches(0.3), Inches(12), Inches(0.8), font_size=28, bold=True, color=NAVY)

    insights = content.get("key_insights", [])
    for i, insight in enumerate(insights[:5]):
        _add_text_box(slide, f"• {insight}", Inches(0.7), Inches(1.3 + i * 1.0), Inches(11.5), Inches(0.9), font_size=15, color=NAVY)


def _build_table_slide(prs: Presentation, content: dict, physicians: list):
    from pptx.util import Inches, Pt
    blank_layout = prs.slide_layouts[6]
    slide = prs.slides.add_slide(blank_layout)
    _set_bg(slide, WHITE)

    _add_text_box(slide, "Top Physicians by Claim Volume", Inches(0.5), Inches(0.3), Inches(12), Inches(0.7), font_size=24, bold=True, color=NAVY)

    top_physicians = content.get("top_physicians", [])[:8]
    if not top_physicians:
        top_physicians = [
            {"name": f"{p['firstName']} {p['lastName']}", "affiliation": p["affiliation"], "claims": p["totalNSCLCClaims"]}
            for p in sorted(physicians, key=lambda x: x.get("totalNSCLCClaims", 0), reverse=True)[:8]
        ]

    rows = len(top_physicians) + 1
    cols = 3
    table = slide.shapes.add_table(rows, cols, Inches(0.5), Inches(1.2), Inches(12.3), Inches(5.8)).table

    headers = ["Physician", "Affiliation", "Total Claims"]
    for col_idx, header in enumerate(headers):
        cell = table.cell(0, col_idx)
        cell.text = header
        cell.fill.solid()
        cell.fill.fore_color.rgb = NAVY
        p = cell.text_frame.paragraphs[0]
        run = p.runs[0] if p.runs else p.add_run()
        run.font.bold = True
        run.font.color.rgb = WHITE
        run.font.size = Pt(13)

    for row_idx, phys in enumerate(top_physicians, start=1):
        row_data = [phys.get("name", ""), phys.get("affiliation", ""), str(phys.get("claims", ""))]
        bg = LIGHT_GREY if row_idx % 2 == 0 else WHITE
        for col_idx, val in enumerate(row_data):
            cell = table.cell(row_idx, col_idx)
            cell.text = val
            cell.fill.solid()
            cell.fill.fore_color.rgb = bg
            p = cell.text_frame.paragraphs[0]
            run = p.runs[0] if p.runs else p.add_run()
            run.font.size = Pt(12)
            run.font.color.rgb = NAVY
